name: Parse-Binary
version: 0.05
abstract: Binary data structure parser
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
